sudo: required
services:
    - docker

before_install:
    - docker build -f Dockerfile.dev  -t lumpa7223/docker-react .

script:
    - docker run -e CI=true lumpa7223/docker-react yarn test

deploy:
    provider: elasticbeanstalk
    region: "ap-northeast-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-northeast-1-038297139811"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"